# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Learning/Learning/Form.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_LearningWindow(object):
    def setupUi(self, LearningWindow):
        LearningWindow.setObjectName("LearningWindow")
        LearningWindow.resize(1109, 671)
        self.centralwidget = QtWidgets.QWidget(LearningWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.matching_GroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.matching_GroupBox.setEnabled(False)
        self.matching_GroupBox.setGeometry(QtCore.QRect(20, 250, 491, 351))
        self.matching_GroupBox.setObjectName("matching_GroupBox")
        self.matching_Process_ComboBox = QtWidgets.QComboBox(self.matching_GroupBox)
        self.matching_Process_ComboBox.setGeometry(QtCore.QRect(10, 40, 221, 22))
        self.matching_Process_ComboBox.setObjectName("matching_Process_ComboBox")
        self.matching_Pattern_ComboBox = QtWidgets.QComboBox(self.matching_GroupBox)
        self.matching_Pattern_ComboBox.setGeometry(QtCore.QRect(260, 40, 221, 22))
        self.matching_Pattern_ComboBox.setObjectName("matching_Pattern_ComboBox")
        self.matching_Process_Label = QtWidgets.QLabel(self.matching_GroupBox)
        self.matching_Process_Label.setGeometry(QtCore.QRect(10, 20, 56, 12))
        self.matching_Process_Label.setObjectName("matching_Process_Label")
        self.matching_Pattern_Label = QtWidgets.QLabel(self.matching_GroupBox)
        self.matching_Pattern_Label.setGeometry(QtCore.QRect(260, 20, 56, 12))
        self.matching_Pattern_Label.setObjectName("matching_Pattern_Label")
        self.matching_Info_Frame = QtWidgets.QFrame(self.matching_GroupBox)
        self.matching_Info_Frame.setEnabled(False)
        self.matching_Info_Frame.setGeometry(QtCore.QRect(0, 90, 491, 251))
        self.matching_Info_Frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.matching_Info_Frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.matching_Info_Frame.setObjectName("matching_Info_Frame")
        self.matching_Assign_PushButton = QtWidgets.QPushButton(self.matching_Info_Frame)
        self.matching_Assign_PushButton.setGeometry(QtCore.QRect(380, 110, 101, 30))
        self.matching_Assign_PushButton.setObjectName("matching_Assign_PushButton")
        self.matching_Pattern_Column_Label = QtWidgets.QLabel(self.matching_Info_Frame)
        self.matching_Pattern_Column_Label.setGeometry(QtCore.QRect(260, 60, 100, 12))
        self.matching_Pattern_Column_Label.setObjectName("matching_Pattern_Column_Label")
        self.matching_Placeholder_Label = QtWidgets.QLabel(self.matching_Info_Frame)
        self.matching_Placeholder_Label.setGeometry(QtCore.QRect(260, 10, 100, 12))
        self.matching_Placeholder_Label.setObjectName("matching_Placeholder_Label")
        self.matching_Placeholder_ComboBox = QtWidgets.QComboBox(self.matching_Info_Frame)
        self.matching_Placeholder_ComboBox.setGeometry(QtCore.QRect(260, 30, 221, 22))
        self.matching_Placeholder_ComboBox.setObjectName("matching_Placeholder_ComboBox")
        self.matching_Pattern_Column_ComboBox = QtWidgets.QComboBox(self.matching_Info_Frame)
        self.matching_Pattern_Column_ComboBox.setGeometry(QtCore.QRect(260, 80, 221, 22))
        self.matching_Pattern_Column_ComboBox.setObjectName("matching_Pattern_Column_ComboBox")
        self.matching_ListWidget = QtWidgets.QListWidget(self.matching_Info_Frame)
        self.matching_ListWidget.setGeometry(QtCore.QRect(10, 10, 221, 191))
        self.matching_ListWidget.setObjectName("matching_ListWidget")
        self.matching_Probability_Column_ComboBox = QtWidgets.QComboBox(self.matching_Info_Frame)
        self.matching_Probability_Column_ComboBox.setEnabled(False)
        self.matching_Probability_Column_ComboBox.setGeometry(QtCore.QRect(260, 180, 221, 22))
        self.matching_Probability_Column_ComboBox.setObjectName("matching_Probability_Column_ComboBox")
        self.matching_Probability_Column_Label = QtWidgets.QLabel(self.matching_Info_Frame)
        self.matching_Probability_Column_Label.setGeometry(QtCore.QRect(260, 160, 111, 16))
        self.matching_Probability_Column_Label.setObjectName("matching_Probability_Column_Label")
        self.matching_Info_Add_PushButton = QtWidgets.QPushButton(self.matching_Info_Frame)
        self.matching_Info_Add_PushButton.setEnabled(False)
        self.matching_Info_Add_PushButton.setGeometry(QtCore.QRect(145, 220, 201, 30))
        self.matching_Info_Add_PushButton.setObjectName("matching_Info_Add_PushButton")
        self.learning_Flow_GroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.learning_Flow_GroupBox.setGeometry(QtCore.QRect(10, 10, 501, 221))
        self.learning_Flow_GroupBox.setObjectName("learning_Flow_GroupBox")
        self.learning_Flow_ListWidget = QtWidgets.QListWidget(self.learning_Flow_GroupBox)
        self.learning_Flow_ListWidget.setGeometry(QtCore.QRect(10, 20, 231, 151))
        self.learning_Flow_ListWidget.setObjectName("learning_Flow_ListWidget")
        self.name_Label = QtWidgets.QLabel(self.learning_Flow_GroupBox)
        self.name_Label.setGeometry(QtCore.QRect(270, 20, 110, 13))
        self.name_Label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.name_Label.setObjectName("name_Label")
        self.name_LineEdit = QtWidgets.QLineEdit(self.learning_Flow_GroupBox)
        self.name_LineEdit.setGeometry(QtCore.QRect(270, 40, 100, 20))
        self.name_LineEdit.setObjectName("name_LineEdit")
        self.checkpoint_Save_LineEdit = QtWidgets.QLineEdit(self.learning_Flow_GroupBox)
        self.checkpoint_Save_LineEdit.setGeometry(QtCore.QRect(270, 90, 100, 20))
        self.checkpoint_Save_LineEdit.setObjectName("checkpoint_Save_LineEdit")
        self.epoch_Label = QtWidgets.QLabel(self.learning_Flow_GroupBox)
        self.epoch_Label.setGeometry(QtCore.QRect(390, 20, 110, 13))
        self.epoch_Label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.epoch_Label.setObjectName("epoch_Label")
        self.epoch_LineEdit = QtWidgets.QLineEdit(self.learning_Flow_GroupBox)
        self.epoch_LineEdit.setGeometry(QtCore.QRect(390, 40, 100, 20))
        self.epoch_LineEdit.setObjectName("epoch_LineEdit")
        self.checkpoint_Interval_Label = QtWidgets.QLabel(self.learning_Flow_GroupBox)
        self.checkpoint_Interval_Label.setGeometry(QtCore.QRect(270, 70, 110, 13))
        self.checkpoint_Interval_Label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.checkpoint_Interval_Label.setObjectName("checkpoint_Interval_Label")
        self.test_Interval_LineEdit = QtWidgets.QLineEdit(self.learning_Flow_GroupBox)
        self.test_Interval_LineEdit.setGeometry(QtCore.QRect(390, 90, 100, 20))
        self.test_Interval_LineEdit.setObjectName("test_Interval_LineEdit")
        self.test_Interval_Label = QtWidgets.QLabel(self.learning_Flow_GroupBox)
        self.test_Interval_Label.setGeometry(QtCore.QRect(390, 70, 110, 13))
        self.test_Interval_Label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.test_Interval_Label.setObjectName("test_Interval_Label")
        self.learning_Flow_Down_PushButton = QtWidgets.QPushButton(self.learning_Flow_GroupBox)
        self.learning_Flow_Down_PushButton.setGeometry(QtCore.QRect(10, 180, 111, 30))
        self.learning_Flow_Down_PushButton.setObjectName("learning_Flow_Down_PushButton")
        self.learning_Flow_Up_PushButton = QtWidgets.QPushButton(self.learning_Flow_GroupBox)
        self.learning_Flow_Up_PushButton.setGeometry(QtCore.QRect(130, 180, 111, 30))
        self.learning_Flow_Up_PushButton.setObjectName("learning_Flow_Up_PushButton")
        self.learning_Flow_Add_PushButton = QtWidgets.QPushButton(self.learning_Flow_GroupBox)
        self.learning_Flow_Add_PushButton.setGeometry(QtCore.QRect(390, 180, 101, 30))
        self.learning_Flow_Add_PushButton.setObjectName("learning_Flow_Add_PushButton")
        self.mini_Batch_Size_Label = QtWidgets.QLabel(self.learning_Flow_GroupBox)
        self.mini_Batch_Size_Label.setGeometry(QtCore.QRect(270, 120, 110, 13))
        self.mini_Batch_Size_Label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.mini_Batch_Size_Label.setObjectName("mini_Batch_Size_Label")
        self.mini_Batch_Size_LineEdit = QtWidgets.QLineEdit(self.learning_Flow_GroupBox)
        self.mini_Batch_Size_LineEdit.setGeometry(QtCore.QRect(270, 140, 100, 20))
        self.mini_Batch_Size_LineEdit.setObjectName("mini_Batch_Size_LineEdit")
        self.use_Probability_Label = QtWidgets.QLabel(self.learning_Flow_GroupBox)
        self.use_Probability_Label.setGeometry(QtCore.QRect(390, 120, 110, 13))
        self.use_Probability_Label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.use_Probability_Label.setObjectName("use_Probability_Label")
        self.use_Probability_ComboBox = QtWidgets.QComboBox(self.learning_Flow_GroupBox)
        self.use_Probability_ComboBox.setGeometry(QtCore.QRect(390, 140, 100, 22))
        self.use_Probability_ComboBox.setObjectName("use_Probability_ComboBox")
        self.info_TabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.info_TabWidget.setGeometry(QtCore.QRect(530, 10, 571, 591))
        self.info_TabWidget.setObjectName("info_TabWidget")
        self.learning_Info_Tab = QtWidgets.QWidget()
        self.learning_Info_Tab.setObjectName("learning_Info_Tab")
        self.learning_Info_TreeWidget = QtWidgets.QTreeWidget(self.learning_Info_Tab)
        self.learning_Info_TreeWidget.setGeometry(QtCore.QRect(10, 10, 551, 551))
        self.learning_Info_TreeWidget.setRootIsDecorated(True)
        self.learning_Info_TreeWidget.setObjectName("learning_Info_TreeWidget")
        self.learning_Info_TreeWidget.header().setVisible(False)
        self.info_TabWidget.addTab(self.learning_Info_Tab, "")
        self.process_Tab = QtWidgets.QWidget()
        self.process_Tab.setObjectName("process_Tab")
        self.process_TabWidget = QtWidgets.QTabWidget(self.process_Tab)
        self.process_TabWidget.setGeometry(QtCore.QRect(10, 10, 551, 551))
        self.process_TabWidget.setObjectName("process_TabWidget")
        self.info_TabWidget.addTab(self.process_Tab, "")
        self.pattern_Tab = QtWidgets.QWidget()
        self.pattern_Tab.setObjectName("pattern_Tab")
        self.pattern_TabWidget = QtWidgets.QTabWidget(self.pattern_Tab)
        self.pattern_TabWidget.setGeometry(QtCore.QRect(10, 10, 551, 551))
        self.pattern_TabWidget.setObjectName("pattern_TabWidget")
        self.info_TabWidget.addTab(self.pattern_Tab, "")
        self.next_PushButton = QtWidgets.QPushButton(self.centralwidget)
        self.next_PushButton.setGeometry(QtCore.QRect(960, 620, 141, 41))
        self.next_PushButton.setObjectName("next_PushButton")
        LearningWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(LearningWindow)
        self.info_TabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(LearningWindow)

    def retranslateUi(self, LearningWindow):
        _translate = QtCore.QCoreApplication.translate
        LearningWindow.setWindowTitle(_translate("LearningWindow", "HNet 2.0 Alpha: Learning"))
        self.matching_GroupBox.setTitle(_translate("LearningWindow", "Matching"))
        self.matching_Process_Label.setText(_translate("LearningWindow", "Process"))
        self.matching_Pattern_Label.setText(_translate("LearningWindow", "Pattern"))
        self.matching_Assign_PushButton.setText(_translate("LearningWindow", "Assign"))
        self.matching_Pattern_Column_Label.setText(_translate("LearningWindow", "Pattern column"))
        self.matching_Placeholder_Label.setText(_translate("LearningWindow", "Placeholder"))
        self.matching_Probability_Column_Label.setText(_translate("LearningWindow", "Probability"))
        self.matching_Info_Add_PushButton.setText(_translate("LearningWindow", "Add"))
        self.learning_Flow_GroupBox.setTitle(_translate("LearningWindow", "Learning flow"))
        self.name_Label.setText(_translate("LearningWindow", "Name"))
        self.epoch_Label.setText(_translate("LearningWindow", "Epoch"))
        self.checkpoint_Interval_Label.setText(_translate("LearningWindow", "Checkpoint Interval"))
        self.test_Interval_Label.setText(_translate("LearningWindow", "Test Interval"))
        self.learning_Flow_Down_PushButton.setText(_translate("LearningWindow", "▼"))
        self.learning_Flow_Up_PushButton.setText(_translate("LearningWindow", "▲"))
        self.learning_Flow_Add_PushButton.setText(_translate("LearningWindow", "Add"))
        self.mini_Batch_Size_Label.setText(_translate("LearningWindow", "Mini batch size"))
        self.use_Probability_Label.setText(_translate("LearningWindow", "Probability"))
        self.learning_Info_TreeWidget.headerItem().setText(0, _translate("LearningWindow", "Root"))
        self.info_TabWidget.setTabText(self.info_TabWidget.indexOf(self.learning_Info_Tab), _translate("LearningWindow", "Learning info."))
        self.info_TabWidget.setTabText(self.info_TabWidget.indexOf(self.process_Tab), _translate("LearningWindow", "Process"))
        self.info_TabWidget.setTabText(self.info_TabWidget.indexOf(self.pattern_Tab), _translate("LearningWindow", "Pattern"))
        self.next_PushButton.setText(_translate("LearningWindow", "Next"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LearningWindow = QtWidgets.QMainWindow()
    ui = Ui_LearningWindow()
    ui.setupUi(LearningWindow)
    LearningWindow.show()
    sys.exit(app.exec_())

