# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Process/Form.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ProcessWindow(object):
    def setupUi(self, ProcessWindow):
        ProcessWindow.setObjectName("ProcessWindow")
        ProcessWindow.resize(1359, 767)
        self.centralwidget = QtWidgets.QWidget(ProcessWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tesnor_Tab_Widget = QtWidgets.QTabWidget(self.centralwidget)
        self.tesnor_Tab_Widget.setEnabled(False)
        self.tesnor_Tab_Widget.setGeometry(QtCore.QRect(520, 10, 831, 701))
        self.tesnor_Tab_Widget.setObjectName("tesnor_Tab_Widget")
        self.custom_Tab = QtWidgets.QWidget()
        self.custom_Tab.setEnabled(False)
        self.custom_Tab.setObjectName("custom_Tab")
        self.function_Add_PushButton = QtWidgets.QPushButton(self.custom_Tab)
        self.function_Add_PushButton.setEnabled(False)
        self.function_Add_PushButton.setGeometry(QtCore.QRect(490, 620, 171, 41))
        self.function_Add_PushButton.setObjectName("function_Add_PushButton")
        self.function_Description_PlainTextEdit = QtWidgets.QPlainTextEdit(self.custom_Tab)
        self.function_Description_PlainTextEdit.setGeometry(QtCore.QRect(330, 30, 481, 201))
        self.function_Description_PlainTextEdit.setReadOnly(True)
        self.function_Description_PlainTextEdit.setObjectName("function_Description_PlainTextEdit")
        self.function_Description_Label = QtWidgets.QLabel(self.custom_Tab)
        self.function_Description_Label.setGeometry(QtCore.QRect(330, 10, 150, 12))
        self.function_Description_Label.setObjectName("function_Description_Label")
        self.parameter_Setup_Label = QtWidgets.QLabel(self.custom_Tab)
        self.parameter_Setup_Label.setGeometry(QtCore.QRect(330, 270, 150, 12))
        self.parameter_Setup_Label.setObjectName("parameter_Setup_Label")
        self.formLayoutWidget = QtWidgets.QWidget(self.custom_Tab)
        self.formLayoutWidget.setGeometry(QtCore.QRect(330, 290, 481, 321))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.function_GroupBox = QtWidgets.QGroupBox(self.custom_Tab)
        self.function_GroupBox.setGeometry(QtCore.QRect(10, 10, 301, 661))
        self.function_GroupBox.setObjectName("function_GroupBox")
        self.rnn_ComboBox = QtWidgets.QComboBox(self.function_GroupBox)
        self.rnn_ComboBox.setGeometry(QtCore.QRect(10, 160, 281, 22))
        self.rnn_ComboBox.setObjectName("rnn_ComboBox")
        self.forward_Label = QtWidgets.QLabel(self.function_GroupBox)
        self.forward_Label.setGeometry(QtCore.QRect(10, 80, 150, 12))
        self.forward_Label.setObjectName("forward_Label")
        self.fundamental_Math_ComboBox = QtWidgets.QComboBox(self.function_GroupBox)
        self.fundamental_Math_ComboBox.setGeometry(QtCore.QRect(10, 330, 281, 22))
        self.fundamental_Math_ComboBox.setObjectName("fundamental_Math_ComboBox")
        self.optimizer_ComboBox = QtWidgets.QComboBox(self.function_GroupBox)
        self.optimizer_ComboBox.setGeometry(QtCore.QRect(10, 450, 281, 22))
        self.optimizer_ComboBox.setObjectName("optimizer_ComboBox")
        self.reshape_ComboBox = QtWidgets.QComboBox(self.function_GroupBox)
        self.reshape_ComboBox.setGeometry(QtCore.QRect(10, 280, 281, 22))
        self.reshape_ComboBox.setObjectName("reshape_ComboBox")
        self.loss_Calc_Label = QtWidgets.QLabel(self.function_GroupBox)
        self.loss_Calc_Label.setGeometry(QtCore.QRect(10, 370, 150, 12))
        self.loss_Calc_Label.setObjectName("loss_Calc_Label")
        self.reshape_Label = QtWidgets.QLabel(self.function_GroupBox)
        self.reshape_Label.setGeometry(QtCore.QRect(10, 260, 150, 12))
        self.reshape_Label.setObjectName("reshape_Label")
        self.other_ComboBox = QtWidgets.QComboBox(self.function_GroupBox)
        self.other_ComboBox.setGeometry(QtCore.QRect(10, 630, 281, 22))
        self.other_ComboBox.setObjectName("other_ComboBox")
        self.fundamental_Math_Label = QtWidgets.QLabel(self.function_GroupBox)
        self.fundamental_Math_Label.setGeometry(QtCore.QRect(10, 310, 150, 16))
        self.fundamental_Math_Label.setObjectName("fundamental_Math_Label")
        self.placeholder_ComboBox = QtWidgets.QComboBox(self.function_GroupBox)
        self.placeholder_ComboBox.setGeometry(QtCore.QRect(10, 40, 281, 22))
        self.placeholder_ComboBox.setObjectName("placeholder_ComboBox")
        self.forward_ComboBox = QtWidgets.QComboBox(self.function_GroupBox)
        self.forward_ComboBox.setGeometry(QtCore.QRect(10, 100, 281, 22))
        self.forward_ComboBox.setObjectName("forward_ComboBox")
        self.other_Label = QtWidgets.QLabel(self.function_GroupBox)
        self.other_Label.setGeometry(QtCore.QRect(10, 610, 150, 12))
        self.other_Label.setObjectName("other_Label")
        self.test_Calc_ComboBox = QtWidgets.QComboBox(self.function_GroupBox)
        self.test_Calc_ComboBox.setGeometry(QtCore.QRect(10, 510, 281, 22))
        self.test_Calc_ComboBox.setObjectName("test_Calc_ComboBox")
        self.test_Calc_Label = QtWidgets.QLabel(self.function_GroupBox)
        self.test_Calc_Label.setGeometry(QtCore.QRect(10, 490, 150, 12))
        self.test_Calc_Label.setObjectName("test_Calc_Label")
        self.placeholder_Label = QtWidgets.QLabel(self.function_GroupBox)
        self.placeholder_Label.setGeometry(QtCore.QRect(10, 20, 150, 12))
        self.placeholder_Label.setObjectName("placeholder_Label")
        self.rnn_Label = QtWidgets.QLabel(self.function_GroupBox)
        self.rnn_Label.setGeometry(QtCore.QRect(10, 140, 150, 16))
        self.rnn_Label.setObjectName("rnn_Label")
        self.activation_Calc_Label = QtWidgets.QLabel(self.function_GroupBox)
        self.activation_Calc_Label.setGeometry(QtCore.QRect(10, 200, 150, 12))
        self.activation_Calc_Label.setObjectName("activation_Calc_Label")
        self.loss_Calc_ComboBox = QtWidgets.QComboBox(self.function_GroupBox)
        self.loss_Calc_ComboBox.setGeometry(QtCore.QRect(10, 390, 281, 22))
        self.loss_Calc_ComboBox.setObjectName("loss_Calc_ComboBox")
        self.optimizer_Label = QtWidgets.QLabel(self.function_GroupBox)
        self.optimizer_Label.setGeometry(QtCore.QRect(10, 430, 150, 12))
        self.optimizer_Label.setObjectName("optimizer_Label")
        self.activation_Calc_ComboBox = QtWidgets.QComboBox(self.function_GroupBox)
        self.activation_Calc_ComboBox.setGeometry(QtCore.QRect(10, 220, 281, 22))
        self.activation_Calc_ComboBox.setObjectName("activation_Calc_ComboBox")
        self.create_ComboBox = QtWidgets.QComboBox(self.function_GroupBox)
        self.create_ComboBox.setGeometry(QtCore.QRect(10, 570, 281, 22))
        self.create_ComboBox.setObjectName("create_ComboBox")
        self.create_Label = QtWidgets.QLabel(self.function_GroupBox)
        self.create_Label.setGeometry(QtCore.QRect(10, 550, 150, 12))
        self.create_Label.setObjectName("create_Label")
        self.tesnor_Tab_Widget.addTab(self.custom_Tab, "")
        self.process_ListWidget = QtWidgets.QListWidget(self.centralwidget)
        self.process_ListWidget.setGeometry(QtCore.QRect(10, 10, 181, 131))
        self.process_ListWidget.setObjectName("process_ListWidget")
        self.process_LineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.process_LineEdit.setGeometry(QtCore.QRect(200, 30, 311, 20))
        self.process_LineEdit.setObjectName("process_LineEdit")
        self.process_Add_PushButton = QtWidgets.QPushButton(self.centralwidget)
        self.process_Add_PushButton.setGeometry(QtCore.QRect(360, 60, 151, 41))
        self.process_Add_PushButton.setObjectName("process_Add_PushButton")
        self.process_Label = QtWidgets.QLabel(self.centralwidget)
        self.process_Label.setGeometry(QtCore.QRect(200, 10, 56, 12))
        self.process_Label.setObjectName("process_Label")
        self.next_PushButton = QtWidgets.QPushButton(self.centralwidget)
        self.next_PushButton.setGeometry(QtCore.QRect(1180, 720, 171, 41))
        self.next_PushButton.setObjectName("next_PushButton")
        self.status_TabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.status_TabWidget.setGeometry(QtCore.QRect(10, 160, 501, 551))
        self.status_TabWidget.setObjectName("status_TabWidget")
        self.graph_Tab = QtWidgets.QWidget()
        self.graph_Tab.setObjectName("graph_Tab")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.graph_Tab)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 481, 511))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.process_GraphicsLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.process_GraphicsLayout.setContentsMargins(0, 0, 0, 0)
        self.process_GraphicsLayout.setObjectName("process_GraphicsLayout")
        self.status_TabWidget.addTab(self.graph_Tab, "")
        self.script_Tab = QtWidgets.QWidget()
        self.script_Tab.setObjectName("script_Tab")
        self.script_PlainTextEdit = QtWidgets.QPlainTextEdit(self.script_Tab)
        self.script_PlainTextEdit.setGeometry(QtCore.QRect(10, 10, 481, 461))
        self.script_PlainTextEdit.setReadOnly(True)
        self.script_PlainTextEdit.setObjectName("script_PlainTextEdit")
        self.script_Save_PushButton = QtWidgets.QPushButton(self.script_Tab)
        self.script_Save_PushButton.setGeometry(QtCore.QRect(90, 480, 151, 41))
        self.script_Save_PushButton.setObjectName("script_Save_PushButton")
        self.script_Load_PushButton = QtWidgets.QPushButton(self.script_Tab)
        self.script_Load_PushButton.setGeometry(QtCore.QRect(260, 480, 151, 41))
        self.script_Load_PushButton.setObjectName("script_Load_PushButton")
        self.status_TabWidget.addTab(self.script_Tab, "")
        ProcessWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(ProcessWindow)
        self.tesnor_Tab_Widget.setCurrentIndex(0)
        self.status_TabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(ProcessWindow)

    def retranslateUi(self, ProcessWindow):
        _translate = QtCore.QCoreApplication.translate
        ProcessWindow.setWindowTitle(_translate("ProcessWindow", "HNet 2.0 Alpha: Process"))
        self.function_Add_PushButton.setText(_translate("ProcessWindow", "Add"))
        self.function_Description_Label.setText(_translate("ProcessWindow", "Function description"))
        self.parameter_Setup_Label.setText(_translate("ProcessWindow", "Parameter setup"))
        self.function_GroupBox.setTitle(_translate("ProcessWindow", "Functions"))
        self.forward_Label.setText(_translate("ProcessWindow", "Forward"))
        self.loss_Calc_Label.setText(_translate("ProcessWindow", "Loss Calc."))
        self.reshape_Label.setText(_translate("ProcessWindow", "Reshape"))
        self.fundamental_Math_Label.setText(_translate("ProcessWindow", "Fundamental Math"))
        self.other_Label.setText(_translate("ProcessWindow", "Other"))
        self.test_Calc_Label.setText(_translate("ProcessWindow", "Test Calc."))
        self.placeholder_Label.setText(_translate("ProcessWindow", "Placeholder"))
        self.rnn_Label.setText(_translate("ProcessWindow", "Recurrent NN"))
        self.activation_Calc_Label.setText(_translate("ProcessWindow", "Activation Calc."))
        self.optimizer_Label.setText(_translate("ProcessWindow", "Optimizer"))
        self.create_Label.setText(_translate("ProcessWindow", "Create"))
        self.tesnor_Tab_Widget.setTabText(self.tesnor_Tab_Widget.indexOf(self.custom_Tab), _translate("ProcessWindow", "Custom"))
        self.process_Add_PushButton.setText(_translate("ProcessWindow", "New process"))
        self.process_Label.setText(_translate("ProcessWindow", "Process"))
        self.next_PushButton.setText(_translate("ProcessWindow", "Next"))
        self.status_TabWidget.setTabText(self.status_TabWidget.indexOf(self.graph_Tab), _translate("ProcessWindow", "Graph"))
        self.script_Save_PushButton.setText(_translate("ProcessWindow", "Script save"))
        self.script_Load_PushButton.setText(_translate("ProcessWindow", "Script load"))
        self.status_TabWidget.setTabText(self.status_TabWidget.indexOf(self.script_Tab), _translate("ProcessWindow", "Script"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ProcessWindow = QtWidgets.QMainWindow()
    ui = Ui_ProcessWindow()
    ui.setupUi(ProcessWindow)
    ProcessWindow.show()
    sys.exit(app.exec_())

