# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Train/Form.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_TrainWindow(object):
    def setupUi(self, TrainWindow):
        TrainWindow.setObjectName("TrainWindow")
        TrainWindow.resize(761, 549)
        self.centralwidget = QtWidgets.QWidget(TrainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.start_PushButton = QtWidgets.QPushButton(self.centralwidget)
        self.start_PushButton.setGeometry(QtCore.QRect(640, 30, 111, 41))
        self.start_PushButton.setObjectName("start_PushButton")
        self.info_TabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.info_TabWidget.setGeometry(QtCore.QRect(10, 10, 621, 501))
        self.info_TabWidget.setObjectName("info_TabWidget")
        self.train_Info_Tab = QtWidgets.QWidget()
        self.train_Info_Tab.setObjectName("train_Info_Tab")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.train_Info_Tab)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 461, 461))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.loss_Flow_Layout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.loss_Flow_Layout.setContentsMargins(0, 0, 0, 0)
        self.loss_Flow_Layout.setObjectName("loss_Flow_Layout")
        self.global_Step_LineEdit = QtWidgets.QLineEdit(self.train_Info_Tab)
        self.global_Step_LineEdit.setGeometry(QtCore.QRect(490, 90, 120, 20))
        self.global_Step_LineEdit.setReadOnly(True)
        self.global_Step_LineEdit.setObjectName("global_Step_LineEdit")
        self.local_Epoch_LineEdit = QtWidgets.QLineEdit(self.train_Info_Tab)
        self.local_Epoch_LineEdit.setGeometry(QtCore.QRect(490, 210, 120, 20))
        self.local_Epoch_LineEdit.setReadOnly(True)
        self.local_Epoch_LineEdit.setObjectName("local_Epoch_LineEdit")
        self.local_Epoch_Label = QtWidgets.QLabel(self.train_Info_Tab)
        self.local_Epoch_Label.setGeometry(QtCore.QRect(490, 190, 121, 12))
        self.local_Epoch_Label.setObjectName("local_Epoch_Label")
        self.pattern_Label = QtWidgets.QLabel(self.train_Info_Tab)
        self.pattern_Label.setGeometry(QtCore.QRect(490, 370, 121, 12))
        self.pattern_Label.setObjectName("pattern_Label")
        self.global_Epoch_LineEdit = QtWidgets.QLineEdit(self.train_Info_Tab)
        self.global_Epoch_LineEdit.setGeometry(QtCore.QRect(490, 30, 120, 20))
        self.global_Epoch_LineEdit.setText("")
        self.global_Epoch_LineEdit.setReadOnly(True)
        self.global_Epoch_LineEdit.setObjectName("global_Epoch_LineEdit")
        self.local_Step_LineEdit = QtWidgets.QLineEdit(self.train_Info_Tab)
        self.local_Step_LineEdit.setGeometry(QtCore.QRect(490, 270, 120, 20))
        self.local_Step_LineEdit.setReadOnly(True)
        self.local_Step_LineEdit.setObjectName("local_Step_LineEdit")
        self.global_Step_Label = QtWidgets.QLabel(self.train_Info_Tab)
        self.global_Step_Label.setGeometry(QtCore.QRect(490, 70, 121, 12))
        self.global_Step_Label.setObjectName("global_Step_Label")
        self.local_Step_Label = QtWidgets.QLabel(self.train_Info_Tab)
        self.local_Step_Label.setGeometry(QtCore.QRect(490, 250, 121, 12))
        self.local_Step_Label.setObjectName("local_Step_Label")
        self.process_Name_LineEdit = QtWidgets.QLineEdit(self.train_Info_Tab)
        self.process_Name_LineEdit.setGeometry(QtCore.QRect(490, 330, 120, 20))
        self.process_Name_LineEdit.setReadOnly(True)
        self.process_Name_LineEdit.setObjectName("process_Name_LineEdit")
        self.global_Epoch_Label = QtWidgets.QLabel(self.train_Info_Tab)
        self.global_Epoch_Label.setGeometry(QtCore.QRect(490, 10, 121, 12))
        self.global_Epoch_Label.setObjectName("global_Epoch_Label")
        self.pattern_Name_LineEdit = QtWidgets.QLineEdit(self.train_Info_Tab)
        self.pattern_Name_LineEdit.setGeometry(QtCore.QRect(490, 390, 120, 20))
        self.pattern_Name_LineEdit.setReadOnly(True)
        self.pattern_Name_LineEdit.setObjectName("pattern_Name_LineEdit")
        self.process_Label = QtWidgets.QLabel(self.train_Info_Tab)
        self.process_Label.setGeometry(QtCore.QRect(490, 310, 121, 12))
        self.process_Label.setObjectName("process_Label")
        self.loss_LineEdit = QtWidgets.QLineEdit(self.train_Info_Tab)
        self.loss_LineEdit.setGeometry(QtCore.QRect(490, 450, 120, 20))
        self.loss_LineEdit.setReadOnly(True)
        self.loss_LineEdit.setObjectName("loss_LineEdit")
        self.loss_Label = QtWidgets.QLabel(self.train_Info_Tab)
        self.loss_Label.setGeometry(QtCore.QRect(490, 430, 121, 12))
        self.loss_Label.setObjectName("loss_Label")
        self.learning_Flow_Index_LineEdit = QtWidgets.QLineEdit(self.train_Info_Tab)
        self.learning_Flow_Index_LineEdit.setGeometry(QtCore.QRect(490, 150, 120, 20))
        self.learning_Flow_Index_LineEdit.setReadOnly(True)
        self.learning_Flow_Index_LineEdit.setObjectName("learning_Flow_Index_LineEdit")
        self.learning_Flow_Index_Label = QtWidgets.QLabel(self.train_Info_Tab)
        self.learning_Flow_Index_Label.setGeometry(QtCore.QRect(490, 130, 121, 16))
        self.learning_Flow_Index_Label.setObjectName("learning_Flow_Index_Label")
        self.info_TabWidget.addTab(self.train_Info_Tab, "")
        self.weight_Tab = QtWidgets.QWidget()
        self.weight_Tab.setObjectName("weight_Tab")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.weight_Tab)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 70, 461, 401))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.weight_Layout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.weight_Layout.setContentsMargins(0, 0, 0, 0)
        self.weight_Layout.setObjectName("weight_Layout")
        self.weight_ComboBox = QtWidgets.QComboBox(self.weight_Tab)
        self.weight_ComboBox.setGeometry(QtCore.QRect(10, 30, 461, 22))
        self.weight_ComboBox.setObjectName("weight_ComboBox")
        self.weight_Label = QtWidgets.QLabel(self.weight_Tab)
        self.weight_Label.setGeometry(QtCore.QRect(10, 10, 121, 16))
        self.weight_Label.setObjectName("weight_Label")
        self.filter_Indexing_GroupBox = QtWidgets.QGroupBox(self.weight_Tab)
        self.filter_Indexing_GroupBox.setGeometry(QtCore.QRect(490, 70, 121, 401))
        self.filter_Indexing_GroupBox.setObjectName("filter_Indexing_GroupBox")
        self.filter_Indexing_From_LineEdit = QtWidgets.QLineEdit(self.filter_Indexing_GroupBox)
        self.filter_Indexing_From_LineEdit.setGeometry(QtCore.QRect(10, 370, 41, 20))
        self.filter_Indexing_From_LineEdit.setText("")
        self.filter_Indexing_From_LineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.filter_Indexing_From_LineEdit.setObjectName("filter_Indexing_From_LineEdit")
        self.filter_Indexing_From_Label = QtWidgets.QLabel(self.filter_Indexing_GroupBox)
        self.filter_Indexing_From_Label.setGeometry(QtCore.QRect(10, 20, 41, 16))
        self.filter_Indexing_From_Label.setAlignment(QtCore.Qt.AlignCenter)
        self.filter_Indexing_From_Label.setObjectName("filter_Indexing_From_Label")
        self.filter_Indexing_From_VerticalSlider = QtWidgets.QSlider(self.filter_Indexing_GroupBox)
        self.filter_Indexing_From_VerticalSlider.setGeometry(QtCore.QRect(10, 40, 41, 321))
        self.filter_Indexing_From_VerticalSlider.setOrientation(QtCore.Qt.Vertical)
        self.filter_Indexing_From_VerticalSlider.setInvertedAppearance(True)
        self.filter_Indexing_From_VerticalSlider.setInvertedControls(True)
        self.filter_Indexing_From_VerticalSlider.setObjectName("filter_Indexing_From_VerticalSlider")
        self.filter_Indexing_To_LineEdit = QtWidgets.QLineEdit(self.filter_Indexing_GroupBox)
        self.filter_Indexing_To_LineEdit.setGeometry(QtCore.QRect(70, 370, 41, 20))
        self.filter_Indexing_To_LineEdit.setText("")
        self.filter_Indexing_To_LineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.filter_Indexing_To_LineEdit.setObjectName("filter_Indexing_To_LineEdit")
        self.filter_Indexing_To_Label = QtWidgets.QLabel(self.filter_Indexing_GroupBox)
        self.filter_Indexing_To_Label.setGeometry(QtCore.QRect(70, 20, 41, 16))
        self.filter_Indexing_To_Label.setAlignment(QtCore.Qt.AlignCenter)
        self.filter_Indexing_To_Label.setObjectName("filter_Indexing_To_Label")
        self.filter_Indexing_To_VerticalSlider = QtWidgets.QSlider(self.filter_Indexing_GroupBox)
        self.filter_Indexing_To_VerticalSlider.setGeometry(QtCore.QRect(70, 40, 41, 321))
        self.filter_Indexing_To_VerticalSlider.setOrientation(QtCore.Qt.Vertical)
        self.filter_Indexing_To_VerticalSlider.setInvertedAppearance(True)
        self.filter_Indexing_To_VerticalSlider.setInvertedControls(True)
        self.filter_Indexing_To_VerticalSlider.setObjectName("filter_Indexing_To_VerticalSlider")
        self.info_TabWidget.addTab(self.weight_Tab, "")
        self.process_Tab = QtWidgets.QWidget()
        self.process_Tab.setObjectName("process_Tab")
        self.process_TabWidget = QtWidgets.QTabWidget(self.process_Tab)
        self.process_TabWidget.setGeometry(QtCore.QRect(10, 10, 601, 461))
        self.process_TabWidget.setObjectName("process_TabWidget")
        self.info_TabWidget.addTab(self.process_Tab, "")
        self.pattern_Tab = QtWidgets.QWidget()
        self.pattern_Tab.setObjectName("pattern_Tab")
        self.pattern_TabWidget = QtWidgets.QTabWidget(self.pattern_Tab)
        self.pattern_TabWidget.setGeometry(QtCore.QRect(10, 10, 601, 461))
        self.pattern_TabWidget.setObjectName("pattern_TabWidget")
        self.info_TabWidget.addTab(self.pattern_Tab, "")
        self.learning_Tab = QtWidgets.QWidget()
        self.learning_Tab.setObjectName("learning_Tab")
        self.learning_Info_TreeWidget = QtWidgets.QTreeWidget(self.learning_Tab)
        self.learning_Info_TreeWidget.setGeometry(QtCore.QRect(10, 10, 601, 461))
        self.learning_Info_TreeWidget.setRootIsDecorated(True)
        self.learning_Info_TreeWidget.setObjectName("learning_Info_TreeWidget")
        self.learning_Info_TreeWidget.header().setVisible(False)
        self.info_TabWidget.addTab(self.learning_Tab, "")
        self.test_Tab = QtWidgets.QWidget()
        self.test_Tab.setObjectName("test_Tab")
        self.test_Info_TreeWidget = QtWidgets.QTreeWidget(self.test_Tab)
        self.test_Info_TreeWidget.setGeometry(QtCore.QRect(10, 10, 601, 461))
        self.test_Info_TreeWidget.setRootIsDecorated(True)
        self.test_Info_TreeWidget.setObjectName("test_Info_TreeWidget")
        self.test_Info_TreeWidget.header().setVisible(False)
        self.info_TabWidget.addTab(self.test_Tab, "")
        self.train_ProgressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.train_ProgressBar.setGeometry(QtCore.QRect(10, 520, 621, 23))
        self.train_ProgressBar.setMaximum(0)
        self.train_ProgressBar.setProperty("value", 0)
        self.train_ProgressBar.setTextVisible(False)
        self.train_ProgressBar.setObjectName("train_ProgressBar")
        self.checkpoint_Save_PushButton = QtWidgets.QPushButton(self.centralwidget)
        self.checkpoint_Save_PushButton.setEnabled(False)
        self.checkpoint_Save_PushButton.setGeometry(QtCore.QRect(640, 130, 111, 41))
        self.checkpoint_Save_PushButton.setObjectName("checkpoint_Save_PushButton")
        TrainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(TrainWindow)
        self.info_TabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(TrainWindow)

    def retranslateUi(self, TrainWindow):
        _translate = QtCore.QCoreApplication.translate
        TrainWindow.setWindowTitle(_translate("TrainWindow", "HNet 2.0 Alpha: Train"))
        self.start_PushButton.setText(_translate("TrainWindow", "Start"))
        self.local_Epoch_Label.setText(_translate("TrainWindow", "Local epoch"))
        self.pattern_Label.setText(_translate("TrainWindow", "Pattern"))
        self.global_Step_Label.setText(_translate("TrainWindow", "Global step"))
        self.local_Step_Label.setText(_translate("TrainWindow", "Local step"))
        self.global_Epoch_Label.setText(_translate("TrainWindow", "Global epoch"))
        self.process_Label.setText(_translate("TrainWindow", "Process"))
        self.loss_Label.setText(_translate("TrainWindow", "Loss"))
        self.learning_Flow_Index_Label.setText(_translate("TrainWindow", "Learning flow index"))
        self.info_TabWidget.setTabText(self.info_TabWidget.indexOf(self.train_Info_Tab), _translate("TrainWindow", "Train info."))
        self.weight_Label.setText(_translate("TrainWindow", "Weight"))
        self.filter_Indexing_GroupBox.setTitle(_translate("TrainWindow", "Filter indexing"))
        self.filter_Indexing_From_Label.setText(_translate("TrainWindow", "From"))
        self.filter_Indexing_To_Label.setText(_translate("TrainWindow", "To"))
        self.info_TabWidget.setTabText(self.info_TabWidget.indexOf(self.weight_Tab), _translate("TrainWindow", "Weight"))
        self.info_TabWidget.setTabText(self.info_TabWidget.indexOf(self.process_Tab), _translate("TrainWindow", "Process"))
        self.info_TabWidget.setTabText(self.info_TabWidget.indexOf(self.pattern_Tab), _translate("TrainWindow", "Pattern"))
        self.learning_Info_TreeWidget.headerItem().setText(0, _translate("TrainWindow", "Root"))
        self.info_TabWidget.setTabText(self.info_TabWidget.indexOf(self.learning_Tab), _translate("TrainWindow", "Learning"))
        self.test_Info_TreeWidget.headerItem().setText(0, _translate("TrainWindow", "Root"))
        self.info_TabWidget.setTabText(self.info_TabWidget.indexOf(self.test_Tab), _translate("TrainWindow", "Test"))
        self.train_ProgressBar.setFormat(_translate("TrainWindow", "%p%"))
        self.checkpoint_Save_PushButton.setText(_translate("TrainWindow", "Checkpoint Save"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TrainWindow = QtWidgets.QMainWindow()
    ui = Ui_TrainWindow()
    ui.setupUi(TrainWindow)
    TrainWindow.show()
    sys.exit(app.exec_())

