# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Learning/Test/Form.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_TestWindow(object):
    def setupUi(self, TestWindow):
        TestWindow.setObjectName("TestWindow")
        TestWindow.resize(1109, 671)
        self.centralwidget = QtWidgets.QWidget(TestWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.test_GroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.test_GroupBox.setGeometry(QtCore.QRect(10, 10, 501, 591))
        self.test_GroupBox.setObjectName("test_GroupBox")
        self.test_ListWidget = QtWidgets.QListWidget(self.test_GroupBox)
        self.test_ListWidget.setGeometry(QtCore.QRect(10, 20, 231, 121))
        self.test_ListWidget.setObjectName("test_ListWidget")
        self.name_Label = QtWidgets.QLabel(self.test_GroupBox)
        self.name_Label.setGeometry(QtCore.QRect(260, 20, 110, 13))
        self.name_Label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.name_Label.setObjectName("name_Label")
        self.name_LineEdit = QtWidgets.QLineEdit(self.test_GroupBox)
        self.name_LineEdit.setGeometry(QtCore.QRect(260, 40, 231, 20))
        self.name_LineEdit.setObjectName("name_LineEdit")
        self.mini_Batch_Size_Label = QtWidgets.QLabel(self.test_GroupBox)
        self.mini_Batch_Size_Label.setGeometry(QtCore.QRect(260, 70, 110, 13))
        self.mini_Batch_Size_Label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.mini_Batch_Size_Label.setObjectName("mini_Batch_Size_Label")
        self.mini_Batch_Size_LineEdit = QtWidgets.QLineEdit(self.test_GroupBox)
        self.mini_Batch_Size_LineEdit.setGeometry(QtCore.QRect(260, 90, 231, 20))
        self.mini_Batch_Size_LineEdit.setObjectName("mini_Batch_Size_LineEdit")
        self.test_Frame = QtWidgets.QFrame(self.test_GroupBox)
        self.test_Frame.setEnabled(False)
        self.test_Frame.setGeometry(QtCore.QRect(0, 160, 501, 431))
        self.test_Frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.test_Frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.test_Frame.setObjectName("test_Frame")
        self.pattern_ComboBox = QtWidgets.QComboBox(self.test_Frame)
        self.pattern_ComboBox.setGeometry(QtCore.QRect(260, 20, 231, 22))
        self.pattern_ComboBox.setObjectName("pattern_ComboBox")
        self.pattern_Label = QtWidgets.QLabel(self.test_Frame)
        self.pattern_Label.setGeometry(QtCore.QRect(260, 0, 56, 12))
        self.pattern_Label.setObjectName("pattern_Label")
        self.get_Tensor_GroupBox = QtWidgets.QGroupBox(self.test_Frame)
        self.get_Tensor_GroupBox.setEnabled(False)
        self.get_Tensor_GroupBox.setGeometry(QtCore.QRect(0, 50, 251, 171))
        self.get_Tensor_GroupBox.setObjectName("get_Tensor_GroupBox")
        self.get_Tensor_Add_PushButton = QtWidgets.QPushButton(self.get_Tensor_GroupBox)
        self.get_Tensor_Add_PushButton.setGeometry(QtCore.QRect(130, 140, 111, 30))
        self.get_Tensor_Add_PushButton.setObjectName("get_Tensor_Add_PushButton")
        self.get_Tensor_ListWidget = QtWidgets.QListWidget(self.get_Tensor_GroupBox)
        self.get_Tensor_ListWidget.setGeometry(QtCore.QRect(10, 20, 231, 81))
        self.get_Tensor_ListWidget.setObjectName("get_Tensor_ListWidget")
        self.get_Tensor_ComboBox = QtWidgets.QComboBox(self.get_Tensor_GroupBox)
        self.get_Tensor_ComboBox.setGeometry(QtCore.QRect(10, 110, 231, 22))
        self.get_Tensor_ComboBox.setObjectName("get_Tensor_ComboBox")
        self.matching_GroupBox = QtWidgets.QGroupBox(self.test_Frame)
        self.matching_GroupBox.setEnabled(False)
        self.matching_GroupBox.setGeometry(QtCore.QRect(0, 230, 501, 161))
        self.matching_GroupBox.setObjectName("matching_GroupBox")
        self.matching_Assign_PushButton = QtWidgets.QPushButton(self.matching_GroupBox)
        self.matching_Assign_PushButton.setGeometry(QtCore.QRect(380, 120, 111, 30))
        self.matching_Assign_PushButton.setObjectName("matching_Assign_PushButton")
        self.matching_Pattern_Column_Label = QtWidgets.QLabel(self.matching_GroupBox)
        self.matching_Pattern_Column_Label.setGeometry(QtCore.QRect(260, 70, 100, 12))
        self.matching_Pattern_Column_Label.setObjectName("matching_Pattern_Column_Label")
        self.matching_Placeholder_Label = QtWidgets.QLabel(self.matching_GroupBox)
        self.matching_Placeholder_Label.setGeometry(QtCore.QRect(260, 20, 100, 12))
        self.matching_Placeholder_Label.setObjectName("matching_Placeholder_Label")
        self.matching_Placeholder_ComboBox = QtWidgets.QComboBox(self.matching_GroupBox)
        self.matching_Placeholder_ComboBox.setGeometry(QtCore.QRect(260, 40, 231, 22))
        self.matching_Placeholder_ComboBox.setObjectName("matching_Placeholder_ComboBox")
        self.matching_ListWidget = QtWidgets.QListWidget(self.matching_GroupBox)
        self.matching_ListWidget.setGeometry(QtCore.QRect(10, 20, 231, 131))
        self.matching_ListWidget.setObjectName("matching_ListWidget")
        self.matching_Pattern_Column_ComboBox = QtWidgets.QComboBox(self.matching_GroupBox)
        self.matching_Pattern_Column_ComboBox.setGeometry(QtCore.QRect(260, 90, 231, 22))
        self.matching_Pattern_Column_ComboBox.setObjectName("matching_Pattern_Column_ComboBox")
        self.process_Label = QtWidgets.QLabel(self.test_Frame)
        self.process_Label.setGeometry(QtCore.QRect(10, 0, 56, 12))
        self.process_Label.setObjectName("process_Label")
        self.attached_Pattern_Column_GroupBox = QtWidgets.QGroupBox(self.test_Frame)
        self.attached_Pattern_Column_GroupBox.setEnabled(False)
        self.attached_Pattern_Column_GroupBox.setGeometry(QtCore.QRect(250, 50, 251, 171))
        self.attached_Pattern_Column_GroupBox.setObjectName("attached_Pattern_Column_GroupBox")
        self.attached_Pattern_Column_Add_PushButton = QtWidgets.QPushButton(self.attached_Pattern_Column_GroupBox)
        self.attached_Pattern_Column_Add_PushButton.setGeometry(QtCore.QRect(130, 140, 111, 30))
        self.attached_Pattern_Column_Add_PushButton.setObjectName("attached_Pattern_Column_Add_PushButton")
        self.attached_Pattern_Column_ListWidget = QtWidgets.QListWidget(self.attached_Pattern_Column_GroupBox)
        self.attached_Pattern_Column_ListWidget.setGeometry(QtCore.QRect(10, 20, 231, 81))
        self.attached_Pattern_Column_ListWidget.setObjectName("attached_Pattern_Column_ListWidget")
        self.attached_Pattern_Column_ComboBox = QtWidgets.QComboBox(self.attached_Pattern_Column_GroupBox)
        self.attached_Pattern_Column_ComboBox.setGeometry(QtCore.QRect(10, 110, 231, 22))
        self.attached_Pattern_Column_ComboBox.setObjectName("attached_Pattern_Column_ComboBox")
        self.test_Add_PushButton = QtWidgets.QPushButton(self.test_Frame)
        self.test_Add_PushButton.setGeometry(QtCore.QRect(380, 400, 111, 30))
        self.test_Add_PushButton.setObjectName("test_Add_PushButton")
        self.process_ComboBox = QtWidgets.QComboBox(self.test_Frame)
        self.process_ComboBox.setGeometry(QtCore.QRect(10, 20, 231, 22))
        self.process_ComboBox.setObjectName("process_ComboBox")
        self.info_TabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.info_TabWidget.setGeometry(QtCore.QRect(530, 10, 571, 591))
        self.info_TabWidget.setObjectName("info_TabWidget")
        self.test_Info_Tab = QtWidgets.QWidget()
        self.test_Info_Tab.setObjectName("test_Info_Tab")
        self.test_Info_TreeWidget = QtWidgets.QTreeWidget(self.test_Info_Tab)
        self.test_Info_TreeWidget.setGeometry(QtCore.QRect(10, 10, 551, 551))
        self.test_Info_TreeWidget.setRootIsDecorated(True)
        self.test_Info_TreeWidget.setObjectName("test_Info_TreeWidget")
        self.test_Info_TreeWidget.header().setVisible(False)
        self.info_TabWidget.addTab(self.test_Info_Tab, "")
        self.process_Tab = QtWidgets.QWidget()
        self.process_Tab.setObjectName("process_Tab")
        self.process_TabWidget = QtWidgets.QTabWidget(self.process_Tab)
        self.process_TabWidget.setGeometry(QtCore.QRect(10, 10, 551, 551))
        self.process_TabWidget.setObjectName("process_TabWidget")
        self.info_TabWidget.addTab(self.process_Tab, "")
        self.pattern_Tab = QtWidgets.QWidget()
        self.pattern_Tab.setObjectName("pattern_Tab")
        self.pattern_TabWidget = QtWidgets.QTabWidget(self.pattern_Tab)
        self.pattern_TabWidget.setGeometry(QtCore.QRect(10, 10, 551, 551))
        self.pattern_TabWidget.setObjectName("pattern_TabWidget")
        self.info_TabWidget.addTab(self.pattern_Tab, "")
        self.next_PushButton = QtWidgets.QPushButton(self.centralwidget)
        self.next_PushButton.setGeometry(QtCore.QRect(960, 620, 141, 41))
        self.next_PushButton.setObjectName("next_PushButton")
        TestWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(TestWindow)
        self.info_TabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(TestWindow)

    def retranslateUi(self, TestWindow):
        _translate = QtCore.QCoreApplication.translate
        TestWindow.setWindowTitle(_translate("TestWindow", "HNet 2.0 Alpha: Test"))
        self.test_GroupBox.setTitle(_translate("TestWindow", "Test"))
        self.name_Label.setText(_translate("TestWindow", "Name"))
        self.mini_Batch_Size_Label.setText(_translate("TestWindow", "Mini batch size"))
        self.pattern_Label.setText(_translate("TestWindow", "Pattern"))
        self.get_Tensor_GroupBox.setTitle(_translate("TestWindow", "Get tensor"))
        self.get_Tensor_Add_PushButton.setText(_translate("TestWindow", "Add"))
        self.matching_GroupBox.setTitle(_translate("TestWindow", "Matching"))
        self.matching_Assign_PushButton.setText(_translate("TestWindow", "Assign"))
        self.matching_Pattern_Column_Label.setText(_translate("TestWindow", "Pattern column"))
        self.matching_Placeholder_Label.setText(_translate("TestWindow", "Placeholder"))
        self.process_Label.setText(_translate("TestWindow", "Process"))
        self.attached_Pattern_Column_GroupBox.setTitle(_translate("TestWindow", "Attached pattern column"))
        self.attached_Pattern_Column_Add_PushButton.setText(_translate("TestWindow", "Add"))
        self.test_Add_PushButton.setText(_translate("TestWindow", "Add"))
        self.test_Info_TreeWidget.headerItem().setText(0, _translate("TestWindow", "Root"))
        self.info_TabWidget.setTabText(self.info_TabWidget.indexOf(self.test_Info_Tab), _translate("TestWindow", "Test info."))
        self.info_TabWidget.setTabText(self.info_TabWidget.indexOf(self.process_Tab), _translate("TestWindow", "Process"))
        self.info_TabWidget.setTabText(self.info_TabWidget.indexOf(self.pattern_Tab), _translate("TestWindow", "Pattern"))
        self.next_PushButton.setText(_translate("TestWindow", "Next"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TestWindow = QtWidgets.QMainWindow()
    ui = Ui_TestWindow()
    ui.setupUi(TestWindow)
    TestWindow.show()
    sys.exit(app.exec_())

